# production: &production
#   adapter: redis
#   url: #heroku
#
# development: &development
#   adapter: redis
#   url: redis://localhost:6379/0
#   # channel_prefix: hu_production
#
# test: *development
